export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDEINTS';
export const FETCH_INGREDIETS_FAILED = 'FETCH_INGREDIETS_FAILED';
